//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTap2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class StudentTable
    {
        public int Id { get; set; }
        [Display(Name = "Mã số sinh viên:")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Student number required!")]
        public string studentNub { get; set; }
        [Display(Name = "Họ tên:")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Student name required!")]
        public string studentName { get; set; }
        [Display(Name = "Điểm:")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Student score required!")]
        public float studentMark { get; set; }
    }
}
